Generates n blobs.
artt/random-shapes pull request #1
Opened 2021-02-02 10:44 UTC by bonafidehan

2021-02-04 02:22 UTC, artt requested changes
Thanks! Looks like you need to add a `return` to make it backward compatible. Function names look not as I initially intended (`H` in `genHLine` came from "horizontal lines" haha) but should be fine for now. Will clean up the code in the next major version (if any).

2021-02-04 02:22 UTC, artt commented on src/index.js
> +	genHBlobs(size, options)
Need to return the 0th element since `genHBlobs` now returns an array.
```suggestion
	return genHBlobs(size, options)[0]
```

2021-02-06 21:28 UTC, bonafidehan commented
Oops thanks for catching that!

2021-02-07 13:51 UTC, artt approved these changes
Looks good!

2021-02-07 13:51 UTC, merged